version: '2.1'

services:
  syslog:
    image: jpvriel/rsyslog
    build:
      context: .
    volumes:
      - syslog_log:/var/log/remote
      - syslog_work:/var/lib/rsyslog
      - syslog_tls:/etc/pki/rsyslog
    stop_grace_period: 1m30s
    mem_limit: 2g

volumes:
  syslog_log:
  syslog_work:
  syslog_tls:
